### ISSUE TITLE
Missing copyright information

### ISSUE THREAD

**Issue by aphedges** [allenai/ScienceWorld#29]
Although [`LICENSE`](https://github.com/allenai/ScienceWorld/blob/ce05307115a099d1cf9d905a4f9d1da47cdf9ddc/LICENSE) makes it clear this project is under Apache 2.0, it's not clear who owns the code. The line `Copyright [yyyy] [name of copyright owner]` is not filled out, which makes it difficult for us to properly record the license of some functions we copied from the examples here. This will matter if/when we ever need to release code that uses ScienceWorld.

Can the line please be filled in?

**Comment by MarcCote** [comment]
Thanks for pointing this out to us.
Added in d5cd96572b725788494f26c24027d2bf4f46e602

**Comment by aphedges** [comment]
Thank you very much!
