### ISSUE TITLE
Gold paths: Some referents are blank

### ISSUE THREAD

**Issue by PeterAJansen** [allenai/ScienceWorld#5]
Reported by Elias: In the gold paths, occasionally some referents are blank (e.g. "pick up <blank>").  The paths still do run successfully, so the issue wasn't discovered until now. 

When creating the gold paths, some code works to try and find unique referents for each object to avoid having to use the ambiguity resolution mechanism (e.g. if there are two apples, instead of giving the command "pick up <apple>", it will find a unique referent for the apple it wants to pick up -- e.g. pick up <apple on counter>").  My initial guess is that there's an edge case in the unique referent generator that's returning blank referents that's causing the issue.

**Comment by MarcCote** [comment]
Tagging @esteng for visibility.

**Comment by PeterAJansen** [comment]
Should be fixed in this PR: https://github.com/allenai/ScienceWorld/pull/7
