### ISSUE TITLE
Question: What exactly is a referent?

### ISSUE THREAD

**Issue by AndKaminer** [allenai/ScienceWorld#65]
I'm sorry to ask a dumb question, but I'm working on docstring now, and I keep seeing 'referent'. I also saw the term in the original paper. I've been looking around the code, and I'm struggling to understand exactly what it means. Can someone explain it to me? Sorry again for the dumb question. I'll have the docstrings done as soon as I get that cleared up.

**Comment by PeterAJansen** [comment]
Hi @AndKaminer, in a text game we have objects, and those objects can be referred to by one or more names.  For example, in ScienceWorld there might be a `pea plant`, and actions (like `take pea plant`) might recognize a number of possible alternate names for that exact same pea plant object.  The list of possible names that refer to the same object in ScienceWorld is its list of 'referents'.  For the pea plant, it might be something like: "pea plant, living thing, object, pea plant on table, living thing on table, object on table".  Some objects have lots of possible different names (i.e. their referent list is long), and for some it's short.  Sorry for the confusion!

**Comment by AndKaminer** [comment]
Ah I understand. I probably should have guessed that, but I wanted to be sure. Thanks for the clarification!
